//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcmeCursos.CursoServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CursoServices.ICursoService")]
    public interface ICursoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudOf_Curso/Get", ReplyAction="http://tempuri.org/ICrudOf_Curso/GetResponse")]
        AcmeCursos.Models.Curso Get(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudOf_Curso/Get", ReplyAction="http://tempuri.org/ICrudOf_Curso/GetResponse")]
        System.Threading.Tasks.Task<AcmeCursos.Models.Curso> GetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudOf_Curso/GetAll", ReplyAction="http://tempuri.org/ICrudOf_Curso/GetAllResponse")]
        AcmeCursos.Models.Curso[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudOf_Curso/GetAll", ReplyAction="http://tempuri.org/ICrudOf_Curso/GetAllResponse")]
        System.Threading.Tasks.Task<AcmeCursos.Models.Curso[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudOf_Curso/Delete", ReplyAction="http://tempuri.org/ICrudOf_Curso/DeleteResponse")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudOf_Curso/Delete", ReplyAction="http://tempuri.org/ICrudOf_Curso/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudOf_Curso/Save", ReplyAction="http://tempuri.org/ICrudOf_Curso/SaveResponse")]
        AcmeCursos.Models.Curso Save(AcmeCursos.Models.Curso entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudOf_Curso/Save", ReplyAction="http://tempuri.org/ICrudOf_Curso/SaveResponse")]
        System.Threading.Tasks.Task<AcmeCursos.Models.Curso> SaveAsync(AcmeCursos.Models.Curso entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/GetCursoComProfessores", ReplyAction="http://tempuri.org/ICursoService/GetCursoComProfessoresResponse")]
        AcmeCursos.Models.Curso GetCursoComProfessores(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/GetCursoComProfessores", ReplyAction="http://tempuri.org/ICursoService/GetCursoComProfessoresResponse")]
        System.Threading.Tasks.Task<AcmeCursos.Models.Curso> GetCursoComProfessoresAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/SaveWithProfessores", ReplyAction="http://tempuri.org/ICursoService/SaveWithProfessoresResponse")]
        AcmeCursos.Models.Curso SaveWithProfessores(AcmeCursos.Models.Curso curso, int[] ProfessorIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICursoService/SaveWithProfessores", ReplyAction="http://tempuri.org/ICursoService/SaveWithProfessoresResponse")]
        System.Threading.Tasks.Task<AcmeCursos.Models.Curso> SaveWithProfessoresAsync(AcmeCursos.Models.Curso curso, int[] ProfessorIds);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICursoServiceChannel : AcmeCursos.CursoServices.ICursoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CursoServiceClient : System.ServiceModel.ClientBase<AcmeCursos.CursoServices.ICursoService>, AcmeCursos.CursoServices.ICursoService {
        
        public CursoServiceClient() {
        }
        
        public CursoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CursoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CursoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CursoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AcmeCursos.Models.Curso Get(int id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<AcmeCursos.Models.Curso> GetAsync(int id) {
            return base.Channel.GetAsync(id);
        }
        
        public AcmeCursos.Models.Curso[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<AcmeCursos.Models.Curso[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public AcmeCursos.Models.Curso Save(AcmeCursos.Models.Curso entity) {
            return base.Channel.Save(entity);
        }
        
        public System.Threading.Tasks.Task<AcmeCursos.Models.Curso> SaveAsync(AcmeCursos.Models.Curso entity) {
            return base.Channel.SaveAsync(entity);
        }
        
        public AcmeCursos.Models.Curso GetCursoComProfessores(int id) {
            return base.Channel.GetCursoComProfessores(id);
        }
        
        public System.Threading.Tasks.Task<AcmeCursos.Models.Curso> GetCursoComProfessoresAsync(int id) {
            return base.Channel.GetCursoComProfessoresAsync(id);
        }
        
        public AcmeCursos.Models.Curso SaveWithProfessores(AcmeCursos.Models.Curso curso, int[] ProfessorIds) {
            return base.Channel.SaveWithProfessores(curso, ProfessorIds);
        }
        
        public System.Threading.Tasks.Task<AcmeCursos.Models.Curso> SaveWithProfessoresAsync(AcmeCursos.Models.Curso curso, int[] ProfessorIds) {
            return base.Channel.SaveWithProfessoresAsync(curso, ProfessorIds);
        }
    }
}
