//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcmeCursos.EstudanteServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EstudanteServices.IEstudanteService")]
    public interface IEstudanteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudOf_Estudante/Get", ReplyAction="http://tempuri.org/ICrudOf_Estudante/GetResponse")]
        AcmeCursos.Models.Estudante Get(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudOf_Estudante/Get", ReplyAction="http://tempuri.org/ICrudOf_Estudante/GetResponse")]
        System.Threading.Tasks.Task<AcmeCursos.Models.Estudante> GetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudOf_Estudante/GetAll", ReplyAction="http://tempuri.org/ICrudOf_Estudante/GetAllResponse")]
        AcmeCursos.Models.Estudante[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudOf_Estudante/GetAll", ReplyAction="http://tempuri.org/ICrudOf_Estudante/GetAllResponse")]
        System.Threading.Tasks.Task<AcmeCursos.Models.Estudante[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudOf_Estudante/Delete", ReplyAction="http://tempuri.org/ICrudOf_Estudante/DeleteResponse")]
        bool Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudOf_Estudante/Delete", ReplyAction="http://tempuri.org/ICrudOf_Estudante/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudOf_Estudante/Save", ReplyAction="http://tempuri.org/ICrudOf_Estudante/SaveResponse")]
        AcmeCursos.Models.Estudante Save(AcmeCursos.Models.Estudante entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrudOf_Estudante/Save", ReplyAction="http://tempuri.org/ICrudOf_Estudante/SaveResponse")]
        System.Threading.Tasks.Task<AcmeCursos.Models.Estudante> SaveAsync(AcmeCursos.Models.Estudante entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstudanteService/GetEstudanteComCursos", ReplyAction="http://tempuri.org/IEstudanteService/GetEstudanteComCursosResponse")]
        AcmeCursos.Models.Estudante GetEstudanteComCursos(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEstudanteService/GetEstudanteComCursos", ReplyAction="http://tempuri.org/IEstudanteService/GetEstudanteComCursosResponse")]
        System.Threading.Tasks.Task<AcmeCursos.Models.Estudante> GetEstudanteComCursosAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEstudanteServiceChannel : AcmeCursos.EstudanteServices.IEstudanteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EstudanteServiceClient : System.ServiceModel.ClientBase<AcmeCursos.EstudanteServices.IEstudanteService>, AcmeCursos.EstudanteServices.IEstudanteService {
        
        public EstudanteServiceClient() {
        }
        
        public EstudanteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EstudanteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstudanteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EstudanteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AcmeCursos.Models.Estudante Get(int id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<AcmeCursos.Models.Estudante> GetAsync(int id) {
            return base.Channel.GetAsync(id);
        }
        
        public AcmeCursos.Models.Estudante[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<AcmeCursos.Models.Estudante[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public bool Delete(int id) {
            return base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
        
        public AcmeCursos.Models.Estudante Save(AcmeCursos.Models.Estudante entity) {
            return base.Channel.Save(entity);
        }
        
        public System.Threading.Tasks.Task<AcmeCursos.Models.Estudante> SaveAsync(AcmeCursos.Models.Estudante entity) {
            return base.Channel.SaveAsync(entity);
        }
        
        public AcmeCursos.Models.Estudante GetEstudanteComCursos(int id) {
            return base.Channel.GetEstudanteComCursos(id);
        }
        
        public System.Threading.Tasks.Task<AcmeCursos.Models.Estudante> GetEstudanteComCursosAsync(int id) {
            return base.Channel.GetEstudanteComCursosAsync(id);
        }
    }
}
